commands =[
    {
        name:"getAll",
        controller:"user",
        method:"get",
        api:"/user",
        middleware:[]
    },
    {
        name:"login",
        controller:"user",
        method:"post",
        api:"/login",
        middleware:[]
    },
    {
        name:"register",
        controller:"user",
        method:"post",
        api:"/register",
        middleware:[]
    },
    {
        name:"verify",
        controller:"user",
        method:"get",
        api:"/verify",
        middleware:[]
    },
    {
        name:"refreshToken",
        controller:"user",
        method:"post",
        api:"/token",
        middleware:[]
    },
]
module.exports= commands